### ISSUE TITLE
Add `operatorsAliases` option to the Sequelize constructor options argument

### ISSUE THREAD

**Issue by modulitos** [types/sequelize#139]
The Sequelize constructors accepts an options argument, which can have a `operatorsAliases` key, found in the table in the docs here: http://docs.sequelizejs.com/class/lib/sequelize.js~Sequelize.html#instance-constructor-constructor

This options should be supported in the Sequelize type definitions as well.

**Comment by LukeSwart** [comment]
Note that if `operatorsAliases` is not set in the options passed to our `Sequelize` constructor, then it's default value is set to `true`. This causes the following error when starting the application:

>sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:236:13

Setting `operatorsAliases` to `false` resolves this security warning. It seems like this will get fixed in Sequelize v5, according to the code here: https://github.com/sequelize/sequelize/blob/master/lib/sequelize.js#L233-L240

So it would be nice to resolve this warning without breaking the compilation.

**Comment by SimonSchick** [comment]
@felixfbecker I believe this was added?
